version: "3.8"
services:
    backend_laravel_api:
        container_name: backend_laravel_api
        build:
            context: .
            dockerfile: Dockerfile
        command: "php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8000:8000
    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: Database
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_ROOT: "root"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    db:
        driver: local
